#!/usr/bin/env bash

tmp_dir=./tmp_ds_data
datasets_dir=./datasets
base_download_url="https://github.com/WickedElm/feature_residuals_for_iot/releases/download/v1.0.0"

# Create data directory if needed
if [ ! -d ${tmp_dir} ];
then
    mkdir ${tmp_dir}
    chmod 755 ${tmp_dir}
fi

echo "Downloading data."

###
# Base datasets files.
###
wget -q ${base_download_url}/datasets.aa
wget -q ${base_download_url}/datasets.ab
wget -q ${base_download_url}/datasets.ac
cat datasets.aa datasets.ab datasets.ac > datasets.tar.gz
tar xfz ./datasets.tar.gz
rm -f datasets.tar.gz 
rm -f datasets.aa datasets.ab datasets.ac

###
# TON-IOT
###
training_file=conference_iot_sf_ton_iot_ae_tuning_train.pkl
validation_file=conference_iot_sf_ton_iot_ae_tuning_validation.pkl
test_file=conference_iot_sf_ton_iot_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

training_file=conference_nf-ton-iot-v2_ae_tuning_train.pkl
validation_file=conference_nf-ton-iot-v2_ae_tuning_validation.pkl
test_file=conference_nf-ton-iot-v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# BOT-IOT
###
training_file=conference_nf-bot-iot-v2_ae_tuning_train.pkl
validation_file=conference_nf-bot-iot-v2_ae_tuning_validation.pkl
test_file=conference_nf-bot-iot-v2_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# IoT23 Scenario 1
###
training_file=conference_iot_sf_scenario_1_ae_tuning_train.pkl
validation_file=conference_iot_sf_scenario_1_ae_tuning_validation.pkl
test_file=conference_iot_sf_scenario_1_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# IoT23 Scenario 13
###
training_file=conference_iot_sf_scenario_13_ae_tuning_train.pkl
validation_file=conference_iot_sf_scenario_13_ae_tuning_validation.pkl
test_file=conference_iot_sf_scenario_13_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# IoT23 Scenario 19
###
training_file=conference_iot_sf_scenario_19_ae_tuning_train.pkl
validation_file=conference_iot_sf_scenario_19_ae_tuning_validation.pkl
test_file=conference_iot_sf_scenario_19_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}

###
# IoT23 Scenario 20
###
training_file=conference_iot_sf_scenario_20_ae_tuning_train.pkl
validation_file=conference_iot_sf_scenario_20_ae_tuning_validation.pkl
test_file=conference_iot_sf_scenario_20_ae_tuning_test.pkl

wget -q ${base_download_url}/${training_file} -O ${tmp_dir}/${training_file}
wget -q ${base_download_url}/${test_file} -O ${tmp_dir}/${test_file}
wget -q ${base_download_url}/${validation_file} -O ${tmp_dir}/${validation_file}
