_target_: models.clf_mlp_experimental.ClfMlpExperimental
_convert_: all

# Parameters
in_dims: 35
feature_transformer: s_feature_transformer.SFeatureTransformer
results_dir: ./
experiment: default
lr: 1e-4
