_target_: models.clf_mlp.ClfMlp
_convert_: all

# Parameters
in_dims: 35
feature_transformer: s_feature_transformer.SFeatureTransformer
threshold_name: no_threshold
results_dir: ./
experiment: default
lr: 1e-4
