_target_: models.mtl_pretrain_rnn_clf.MtlPretrainRnnClf
_convert_: all

# Parameters
in_dims: 35
clf_input_type: X
pretraining_epochs: 500
results_dir: ./
ae_lr: 1.0
rnn_lr: 0.001
in_hidden_dim: 12
rnn_hidden_size: 10
use_pretrained_ae: False
model_search_path: .
root_dir: /home/lew/Documents/school/research/research_code
rnn_nonlinearity: tanh
rnn_num_layers: 1
rnn_dropout: 0.0
