_target_: models.mtl_pretrain_gru_clf.MtlPretrainGruClf
_convert_: all

# Parameters
in_dims: 35
clf_input_type: X
pretraining_epochs: 500
results_dir: ./
ae_lr: 1.0
gru_lr: 0.001
in_hidden_dim: 12
gru_hidden_size: 10
use_pretrained_ae: False
model_search_path: .
root_dir: /home/lew/Documents/school/research/research_code
gru_num_layers: 1
gru_dropout: 0.0
