_target_: models.multitask_ae_mlp_3_benign_loss.MultitaskAeMlp3BenignLoss
_convert_: all

# Parameters
in_dims: 35
num_layers: 6
feature_transformer: s_feature_transformer.SFeatureTransformer
threshold_name: no_threshold
clf_input_type: X
results_dir: './'
lr: 1.0
lambda_filter: 1.0
in_hidden_dim: 12
