_target_: models.robust_autoencoder_outlier_static_tests.RobustAutoencoderOutlierStaticTests
_convert_: all

# Parameters
in_dims: 29
layer_dims: [22, 15, 8]
results_dir: './'
lr: 1e-4
lambda_filter: 0.01
dropout_rate: 0.5
