_target_: models.robust_autoencoder_bottleneck.RobustAutoencoderBottleneck17
_convert_: all

# Parameters
in_dims: 35
layer_dims: [28, 21, 17]
results_dir: './'
lr: 1e-4
lambda_filter: 0.01
dropout_rate: 0.5
